"""Pure constructed RGB/geometry controls; no images, PDFs, native code or OCR.

Fixtures pass the real raster-view builder/validator. Numeric expectations are
hand-calculated, not generated by the measurement implementation under test.
These observations do not establish real scan quality or representative gain.
"""

import ast
import builtins
from copy import deepcopy
import hashlib
import inspect
import json
from pathlib import Path

import pytest

import ocr_crop_quality as quality
from ocr_crop_raster_view import build_raster_view


def encoded(value):
    return json.dumps(value, sort_keys=True, ensure_ascii=False, allow_nan=False,
                      separators=(",", ":")).encode("utf-8")


def retag(value, key):
    value[key] = hashlib.sha256(encoded({k: v for k, v in value.items() if k != key})).hexdigest()
    return value


def fixture(width=4, height=4, *, gray=None, rgb=None, profile="dpi288", clip=None,
            pixels=None, native_clip=None, display=None, rotation=0):
    scale = {"fit": 2.0, "dpi288": 4.0, "dpi576": 8.0}[profile]
    clip = list(clip or [0.0, 0.0, width / scale, height / scale])
    display = list(display or [0.0, 0.0, 512.0, 512.0])
    dw, dh = display[2] - display[0], display[3] - display[1]
    cropbox = [16.0, 32.0, 16.0 + (dh if rotation in (90, 270) else dw),
               32.0 + (dw if rotation in (90, 270) else dh)]
    scope = retag({"source_sha256": "a" * 64, "page_count": 2, "page_number": 2,
        "coordinate_system": "original_page_display_fraction",
        "bbox": [(clip[i] - display[i % 2]) / (dw if i % 2 == 0 else dh) for i in range(4)],
        "page_geometry": {"display_rect_points": display, "cropbox_points": cropbox,
                          "rotation_degrees": rotation}}, "scope_sha256")
    if rgb is None:
        rgb = bytes(channel for level in (gray if gray is not None else [128] * (width * height))
                    for channel in (level, level, level))
    matrix = [scale, 0.0, 0.0, scale, 0.0, 0.0]
    native = list(clip if native_clip is None else native_clip)
    view = build_raster_view(scope=scope, preview_profile=profile, command_clip=clip,
        command_matrix=matrix, native_clip=native, native_matrix=matrix,
        projected_rect=[value * scale for value in native], pixel_rect=list(pixels or [0, 0, width, height]),
        width=width, height=height, rgb_sha256=hashlib.sha256(rgb).hexdigest())
    return rgb, scope, view


def observe(case):
    rgb, scope, view = case
    return quality.inspect_crop_pixels(rgb, scope=scope, raster_view=view)


def edge_map(result):
    return {edge["edge"]: edge for edge in result["edges"]}


def test_exact_rgb_grayscale_coefficients_and_adjacent_pairs_without_wrap():
    result = observe(fixture(4, 1, rgb=bytes([255, 0, 0, 0, 255, 0, 0, 0, 255, 255, 255, 255])))
    values = result["measurements"]
    assert {i: n for i, n in enumerate(values["histogram"]) if n} == {29: 1, 77: 1, 149: 1, 255: 1}
    assert (values["min"], values["max"], values["p05"], values["p95"]) == (29, 255, 29, 255)
    assert values["horizontal_gradient"] == {"sum": 418, "count": 3}
    assert values["vertical_gradient"] == {"sum": 0, "count": 0}
    assert result["status"] == "ambiguous"
    assert "adjacent_pairs_unavailable_on_an_axis" in result["reasons"]


def test_exact_histogram_gradient_and_global_quarter_range_edge_counts():
    result = observe(fixture(4, 2, gray=[0, 10, 20, 30, 40, 50, 60, 255]))
    values = result["measurements"]
    assert values["sample_count"] == 8 and sum(values["histogram"]) == 8
    assert values["horizontal_gradient"] == {"sum": 245, "count": 6}
    assert values["vertical_gradient"] == {"sum": 345, "count": 4}
    assert (values["min"], values["max"], values["p05"], values["p95"]) == (0, 255, 0, 255)
    edges = edge_map(result)
    assert [(edges[name]["low_extreme_count"], edges[name]["high_extreme_count"])
            for name in ("left", "top", "right", "bottom")] == [(4, 0), (7, 1), (3, 1), (7, 1)]
    assert result["work"]["edge_sample_visits"] == 24  # Corners count independently.
    assert result["work"]["sample_visits"] == 32


def test_percentiles_use_exact_nearest_rank_not_interpolation():
    values = observe(fixture(5, 4, gray=list(range(20))))["measurements"]
    assert (values["p05"], values["p95"]) == (0, 18)
    assert values["histogram"] == [1] * 20 + [0] * 236


@pytest.mark.parametrize("level", [0, 127, 255])
def test_uniform_is_ambiguous_not_clear_and_polarity_counts_are_undefined(level):
    result = observe(fixture(gray=[level] * 16))
    assert result["status"] == "ambiguous" and result["reasons"] == ["uniform_raster"]
    assert result["measurements"]["horizontal_gradient"] == {"sum": 0, "count": 12}
    for edge in result["edges"]:
        assert edge["status"] == "ambiguous"
        assert edge["low_extreme_count"] is None and edge["high_extreme_count"] is None
        assert "uniform_raster_no_polarity_range" in edge["reasons"]
    assert "edge_extremes_require_visual_review_not_clipping_proof" not in result["advice_codes"]


def test_one_pixel_has_four_independent_ambiguous_bands_not_safe_zeros():
    result = observe(fixture(1, 1))
    assert result["status"] == "ambiguous"
    assert result["work"]["auxiliary_gray_bytes"] == 1
    assert result["work"]["edge_sample_visits"] == 4
    assert all(edge["available_sample_count"] == 1 and edge["status"] == "ambiguous"
               for edge in result["edges"])


def test_valid_tiny_scope_with_no_centers_retains_empty_edge_unavailability():
    result = observe(fixture(1, 1, clip=[.015625, .015625, .03125, .03125]))
    assert result["requested_pixel_bbox"] == [.0625, .0625, .125, .125]
    for edge in result["edges"]:
        assert edge["status"] == "unavailable"
        assert edge["ideal_sample_count"] == edge["available_sample_count"] == 0
        assert edge["available_pixel_box"] == [0, 0, 0, 0]
        assert edge["min"] is None and edge["low_extreme_count"] is None
        assert edge["geometric_missing_coverage"] is False
    assert "empty_edge_samples" in result["reasons"]


def test_half_open_fractional_edges_exclude_neighbor_row_column_and_include_low_ties():
    # Requested [.5,.5,4.5,4.5]; centers .5 are included, 4.5 excluded.
    # Dark outer row/column are present in the admitted raster but not any band.
    gray = [255 if x < 4 and y < 4 else 0 for y in range(5) for x in range(5)]
    result = observe(fixture(5, 5, gray=gray, clip=[.125, .125, 1.125, 1.125]))
    assert result["requested_pixel_bbox"] == [.5, .5, 4.5, 4.5]
    expected = {"left": [0, 0, 2, 4], "top": [0, 0, 4, 2],
                "right": [2, 0, 4, 4], "bottom": [0, 2, 4, 4]}
    for edge in result["edges"]:
        assert edge["available_pixel_box"] == expected[edge["edge"]]
        assert edge["ideal_sample_count"] == edge["available_sample_count"] == 8
        assert edge["low_extreme_count"] == 0 and edge["high_extreme_count"] == 8
        assert edge["geometric_missing_coverage"] is False
        assert edge["status"] == "ambiguous"  # Uniform band, not clear.
    assert result["measurements"]["histogram"][0] == 9


def test_tolerance_contraction_geometry_missing_even_without_missing_centers():
    # Same explicit dyadic tolerance example retained in the pure raster suite;
    # constructed declaration only, not a new native-render observation.
    delta = .000244140625
    result = observe(fixture(32, 32, profile="fit", clip=[delta, delta, 16 + delta, 16 + delta]))
    assert result["requested_pixel_bbox"] == [.00048828125, .00048828125, 32.00048828125, 32.00048828125]
    for edge in result["edges"]:
        assert edge["ideal_sample_count"] == edge["available_sample_count"] == 64
        assert edge["missing_sample_count"] == 0
        assert edge["geometric_missing_coverage"] is True and edge["status"] == "partial"
    assert "partial_edge_geometry" in result["reasons"]


def test_native_rounding_partial_centers_have_exact_ideal_and_available_denominators():
    # Explicit binary32 nearest rounding of -8388608.375 to -8388608.0.
    clip = [-8388608.375, -8388608.375, -8388592.0, -8388592.0]
    result = observe(fixture(32, 32, profile="fit", clip=clip,
        native_clip=[-8388608.0, -8388608.0, -8388592.0, -8388592.0],
        pixels=[-16777216, -16777216, -16777184, -16777184],
        display=[-8388609.0, -8388609.0, -8388545.0, -8388545.0]))
    assert result["requested_pixel_bbox"] == [-.75, -.75, 32.0, 32.0]
    edges = edge_map(result)
    assert [(edges[name]["ideal_sample_count"], edges[name]["available_sample_count"],
             edges[name]["missing_sample_count"]) for name in ("left", "top", "right", "bottom")] == [
                 (66, 32, 34), (66, 32, 34), (66, 64, 2), (66, 64, 2)]
    assert all(edge["status"] == "partial" for edge in result["edges"])


@pytest.mark.parametrize("rotation", [0, 90, 180, 270])
def test_cropbox_rotation_and_asymmetry_do_not_rotate_display_pixels_again(rotation):
    result = observe(fixture(8, 4, rotation=rotation, clip=[16.0, 32.0, 18.0, 33.0],
                             pixels=[64, 128, 72, 132], gray=list(range(32)),
                             display=[0.0, 0.0, 512.0, 256.0]))
    assert result["requested_pixel_bbox"] == [0.0, 0.0, 8.0, 4.0]
    assert [edge["available_sample_count"] for edge in result["edges"]] == [8, 16, 8, 16]
    assert result["measurements"]["horizontal_gradient"] == {"sum": 28, "count": 28}
    assert result["measurements"]["vertical_gradient"] == {"sum": 192, "count": 24}


@pytest.mark.parametrize("name,gray", [
    ("sparse", [255] * 99 + [0]),
    ("reversed", [0] * 99 + [255]),
    ("faint", [127, 128] * 50),
    ("rule", [0] * 10 + [255] * 90),
    ("checker_nontext", [0, 255] * 50),
])
def test_appearance_controls_never_become_text_blur_safe_or_confidence_classifications(name, gray):
    result = observe(fixture(10, 10, gray=gray))
    assert result["recipe"]["annotation_policy"] == "annots_on_rendered_appearance_only"
    assert result["recipe"]["acquisition_resolution"] == "unknown"
    assert "measurements_are_not_text_or_accuracy" in result["advice_codes"]
    assert not ({"safe", "clear", "text", "blur", "quality_score", "confidence"} & set(result))
    if name in ("sparse", "reversed"):
        assert result["status"] == "ambiguous" and "percentile_range_collapsed" in result["reasons"]


def test_reversal_swaps_polarity_hypotheses_without_changing_gradients():
    gray = [0, 10, 20, 30, 40, 50, 60, 255]
    first, second = (observe(fixture(4, 2, gray=values)) for values in (gray, [255 - n for n in gray]))
    assert first["measurements"]["horizontal_gradient"] == second["measurements"]["horizontal_gradient"]
    for before, after in zip(first["edges"], second["edges"]):
        assert before["low_extreme_count"] == after["high_extreme_count"]
        assert before["high_extreme_count"] == after["low_extreme_count"]


def test_profiles_bind_distinct_render_specific_measurements_not_acquisition_ppi():
    results = []
    for profile, scale in (("fit", 2), ("dpi288", 4), ("dpi576", 8)):
        results.append(observe(fixture(scale * 2, scale, profile=profile)))
    assert [result["binding"]["preview_profile"] for result in results] == ["fit", "dpi288", "dpi576"]
    assert len({result["binding"]["scope_sha256"] for result in results}) == 1
    assert len({result["observation_sha256"] for result in results}) == 3
    assert all(result["recipe"]["acquisition_resolution"] == "unknown" for result in results)


@pytest.mark.parametrize("bad", [None, [], "pixels", bytearray(48), memoryview(b"\0" * 48), 48, True])
def test_rgb_requires_exact_immutable_bytes_before_traversal(monkeypatch, bad):
    _, scope, view = fixture()
    monkeypatch.setattr(quality, "_measure", lambda *_: pytest.fail("measurement before admission"))
    with pytest.raises(ValueError, match="^invalid crop pixel advisory input or binding$"):
        quality.inspect_crop_pixels(bad, scope=scope, raster_view=view)


def test_bytes_subclass_is_not_admitted(monkeypatch):
    class HostileBytes(bytes):
        def __len__(self):
            pytest.fail("subclass code called")
    rgb, scope, view = fixture()
    with pytest.raises(ValueError, match="advisory input"):
        quality.inspect_crop_pixels(HostileBytes(rgb), scope=scope, raster_view=view)


@pytest.mark.parametrize("change", ["short", "long", "same_length_wrong_rgb", "wrong_rgb_hash"])
def test_length_and_hash_fail_before_grayscale_allocation_or_pixel_measurement(monkeypatch, change):
    rgb, scope, view = fixture()
    if change == "short":
        rgb = rgb[:-1]
    elif change == "long":
        rgb += b"\0"
    elif change == "same_length_wrong_rgb":
        rgb = bytes([129]) + rgb[1:]
    else:
        view["rgb_sha256"] = "b" * 64
        retag(view, "view_sha256")
    monkeypatch.setattr(quality, "_measure", lambda *_: pytest.fail("measurement before byte binding"))
    monkeypatch.setattr(quality, "bytearray", lambda *_: pytest.fail("gray allocated"), raising=False)
    with pytest.raises(ValueError, match="advisory input"):
        quality.inspect_crop_pixels(rgb, scope=scope, raster_view=view)


@pytest.mark.parametrize("target", ["scope", "view"])
@pytest.mark.parametrize("change", ["extra", "missing", "wrong_type"])
def test_top_level_cardinality_and_type_refuse_before_hashing_or_membership(monkeypatch, target, change):
    rgb, scope, view = fixture()
    selected = scope if target == "scope" else view
    if change == "extra":
        selected["extra"] = object()
    elif change == "missing":
        selected.pop("source_sha256")
    else:
        selected = []
        if target == "scope":
            scope = selected
        else:
            view = selected
    monkeypatch.setattr(quality.hashlib, "sha256", lambda *_: pytest.fail("hashed malformed cardinality"))
    with pytest.raises(ValueError, match="advisory input"):
        quality.inspect_crop_pixels(rgb, scope=scope, raster_view=view)


@pytest.mark.parametrize("target,path,value", [
    ("view", ("width",), True), ("view", ("width",), 1401),
    ("view", ("height",), 1401), ("view", ("mode",), "L"),
    ("view", ("preview_profile",), "dpi300"), ("view", ("view_sha256",), "f" * 64),
    ("view", ("rgb_sha256",), "A" * 64), ("view", ("source_sha256",), "c" * 64),
    ("view", ("scope_sha256",), "d" * 64), ("view", ("pixel_rect", 0), 1),
    ("view", ("command_clip", 0), float("inf")),
    ("view", ("native_matrix", 0), float("nan")),
    ("view", ("page_geometry", "extra"), 1),
    ("scope", ("bbox", 0), -0.0), ("scope", ("bbox", 0), .125),
    ("scope", ("page_count",), True), ("scope", ("page_number",), 3),
    ("scope", ("page_geometry", "rotation_degrees"), 45),
    ("scope", ("source_sha256",), "\ud800"),
])
def test_invalid_nested_types_geometry_and_hashes_are_static_before_measurement(monkeypatch, target, path, value):
    rgb, scope, view = fixture()
    destination = scope if target == "scope" else view
    for part in path[:-1]:
        destination = destination[part]
    destination[path[-1]] = value
    monkeypatch.setattr(quality, "_measure", lambda *_: pytest.fail("measured invalid metadata"))
    with pytest.raises(ValueError, match="^invalid crop pixel advisory input or binding$"):
        quality.inspect_crop_pixels(rgb, scope=scope, raster_view=view)


@pytest.mark.parametrize("failure", [KeyboardInterrupt(), SystemExit(3), MemoryError("bounded allocation failed")])
def test_measurement_cancellation_and_allocation_failure_keep_identity(monkeypatch, failure):
    case = fixture()
    def fail(*_):
        raise failure
    monkeypatch.setattr(quality, "_measure", fail)
    with pytest.raises(type(failure)) as observed:
        observe(case)
    assert observed.value is failure


def test_worst_admitted_raster_uses_one_auxiliary_byte_per_pixel_and_bounded_passes(monkeypatch):
    count = 1400 * 1400
    case = fixture(1400, 1400, rgb=b"\x80" * (3 * count))
    allocations = []
    def allocate(size):
        allocations.append(size)
        return builtins.bytearray(size)
    monkeypatch.setattr(quality, "bytearray", allocate, raising=False)
    result = observe(case)
    assert allocations == [count]
    assert result["work"]["auxiliary_gray_bytes"] == count == quality.MAX_PREVIEW_PIXELS
    assert result["work"]["edge_sample_visits"] == 11200
    assert result["work"]["sample_visits"] == count + 11200 <= quality.MAX_SAMPLE_VISITS
    assert result["work"]["adjacent_pair_visits"] == 3917200 <= quality.MAX_ADJACENT_PAIR_VISITS
    assert result["measurements"]["horizontal_gradient"] == {"sum": 0, "count": 1958600}
    assert result["measurements"]["vertical_gradient"] == {"sum": 0, "count": 1958600}
    assert len(encoded(result)) <= 16 * 1024


def test_result_schema_hash_and_all_nested_mutability_are_detached():
    case = fixture(gray=list(range(16)))
    original_rgb, scope, view = case
    before = encoded([scope, view])
    result = observe(case)
    assert set(result) == {"schema_version", "kind", "recipe", "binding", "requested_pixel_bbox",
        "status", "reasons", "measurements", "edges", "advice_codes", "work", "observation_sha256"}
    assert result["binding"] == {key: view[key] for key in ("source_sha256", "scope_sha256", "view_sha256",
        "rgb_sha256", "preview_profile", "width", "height")} | {"page_number": 2}
    expected_hash = hashlib.sha256(b"rag-pipeline:ocr-crop-quality-observation:v1\0" + encoded(
        {key: value for key, value in result.items() if key != "observation_sha256"})).hexdigest()
    assert result["observation_sha256"] == expected_hash
    assert result == json.loads(encoded(result)) and result == observe(case)
    saved = deepcopy(result)
    result["recipe"]["histogram_bins"] = 0
    result["binding"]["source_sha256"] = "f" * 64
    result["measurements"]["histogram"][0] = 100
    result["edges"][0]["available_pixel_box"][0] = 100
    result["requested_pixel_bbox"][0] = 100.0
    assert encoded([scope, view]) == before and case[0] is original_rgb
    assert observe(case) == saved


def test_module_has_only_declared_inward_and_stdlib_imports_without_native_ui_routes():
    source = Path(inspect.getfile(quality)).read_text(encoding="utf-8")
    tree = ast.parse(source)
    modules = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            modules.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            modules.add(node.module)
    assert modules == {"__future__", "hashlib", "json", "math", "ocr_crop_comparison", "ocr_crop_raster_view"}
    assert not any(isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
                   and node.func.id in {"eval", "exec", "__import__", "open"} for node in ast.walk(tree))
