"""Generated byte snapshots and private publication; no PDF parsing or OCR."""

import hashlib
import itertools
import json
import os
from pathlib import Path
import stat
import subprocess
import sys

import pytest

import chunking_core
import cleanup_audit
import cleanup_audit_io as io
import ocr_recovery
import storage_policy
from test_cleanup_audit import plan, recovery


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def dump(path, payload):
    path.write_text(json.dumps(payload, ensure_ascii=False) + "\n", encoding="utf-8")


@pytest.fixture
def inputs(tmp_path, monkeypatch):
    paths = {key: tmp_path / (key + suffix) for key, suffix in (
        ("pdf", ".pdf"), ("recovery", ".json"), ("plan", ".json"), ("output", ".json"),
        ("audit_code", ".py"), ("normalizer_code", ".py"))}
    paths["pdf"].write_bytes(b"SYNTHETIC PDF BYTES - NOT PARSED")
    paths["audit_code"].write_bytes(b"# synthetic source generation\n")
    paths["normalizer_code"].write_bytes(b"# synthetic normalizer generation\n")
    monkeypatch.setattr(cleanup_audit, "__file__", str(paths["audit_code"]))
    monkeypatch.setattr(chunking_core, "__file__", str(paths["normalizer_code"]))
    text = "Synthetic\u00a0text.\n42\nRepeated\nRepeated"
    saved = recovery(text)
    saved["source_sha256"] = digest(paths["pdf"])
    dump(paths["recovery"], saved)
    recipe = plan(text)
    recipe.update(source_sha256=digest(paths["pdf"]), recovery_sha256=digest(paths["recovery"]))
    dump(paths["plan"], recipe)
    return paths


def run(paths):
    return io.audit_cleanup_files(*(paths[key] for key in ("pdf", "recovery", "plan", "output")))


def test_private_exact_source_report_plan_and_implementation_bindings(inputs):
    before = {key: path.read_bytes() for key, path in inputs.items() if key != "output"}
    result = run(inputs)
    assert result["summary"]["changed"] == 1
    assert result["inputs"] == {key + "_sha256": digest(inputs[key]) for key in ("pdf", "recovery", "plan")}
    assert result["implementation"]["cleanup_audit_sha256"] == digest(inputs["audit_code"])
    assert result["implementation"]["chunking_core_sha256"] == digest(inputs["normalizer_code"])
    assert json.loads(inputs["output"].read_bytes()) == result
    assert all(path.read_bytes() == before[key] for key, path in inputs.items() if key != "output")
    if os.name == "nt":
        assert storage_policy.windows_path_is_private(inputs["output"], directory=False)
    else:
        assert stat.S_IMODE(inputs["output"].stat().st_mode) == 0o600


@pytest.mark.parametrize("first,second", list(itertools.combinations(("pdf", "recovery", "plan", "output"), 2)))
def test_aliases_rejected_before_input_reads(inputs, monkeypatch, first, second):
    inputs[second] = inputs[first]
    monkeypatch.setattr(io, "_snapshot", lambda *_a, **_k: pytest.fail("read before path checks"))
    with pytest.raises(ValueError):
        run(inputs)


def test_hardlinked_files_and_symlinks_rejected(inputs, tmp_path):
    alias = tmp_path / "alias"
    try:
        os.link(inputs["plan"], alias)
    except OSError:
        pytest.skip("hardlinks unavailable")
    with pytest.raises(ValueError):
        run(inputs)
    link = tmp_path / "symlink"
    try:
        link.symlink_to(inputs["pdf"])
    except OSError:
        return
    with pytest.raises((ValueError, OSError)):
        io._snapshot(link, 1024, json_input=False)


def test_output_exists_is_preserved_without_loading(inputs, monkeypatch):
    inputs["output"].write_bytes(b"OWNER CONTENT")
    monkeypatch.setattr(io, "_snapshot", lambda *_a, **_k: pytest.fail("read before create-only check"))
    with pytest.raises(FileExistsError):
        run(inputs)
    assert inputs["output"].read_bytes() == b"OWNER CONTENT"


def test_noncooperating_output_creator_is_not_overwritten(inputs, monkeypatch):
    original = ocr_recovery._publish_new_report

    def race(temporary, destination):
        destination.write_bytes(b"RACER")
        original(temporary, destination)

    monkeypatch.setattr(ocr_recovery, "_publish_new_report", race)
    with pytest.raises(FileExistsError):
        run(inputs)
    assert inputs["output"].read_bytes() == b"RACER"


@pytest.mark.parametrize("key", ["pdf", "recovery", "plan", "audit_code", "normalizer_code"])
@pytest.mark.parametrize("stage", ["build", "writer"])
def test_all_generations_rechecked_inside_actual_commit(inputs, monkeypatch, key, stage):
    if stage == "build":
        original = cleanup_audit.build_cleanup_audit

        def changed(*args, **kwargs):
            report = original(*args, **kwargs)
            inputs[key].write_bytes(inputs[key].read_bytes() + b" ")
            return report

        monkeypatch.setattr(cleanup_audit, "build_cleanup_audit", changed)
    else:
        original = storage_policy.atomic_write_private_json

        def changed(path, report, **kwargs):
            commit = kwargs["replace_fn"]

            def changed_at_commit(temporary, destination):
                inputs[key].write_bytes(inputs[key].read_bytes() + b" ")
                commit(temporary, destination)

            kwargs["replace_fn"] = changed_at_commit
            return original(path, report, **kwargs)

        monkeypatch.setattr(storage_policy, "atomic_write_private_json", changed)
    with pytest.raises((ValueError, RuntimeError)):
        run(inputs)
    assert not inputs["output"].exists()


@pytest.mark.parametrize("raw", [b'{"a":1,"a":2}', b'{"a":NaN}', b'{"a":1e999}', b'{', b'\xff', b'[]', b'"x"'])
def test_strict_json_is_bounded_and_sanitized(inputs, raw):
    inputs["plan"].write_bytes(raw)
    with pytest.raises(ValueError) as caught:
        run(inputs)
    assert str(inputs["plan"]) not in str(caught.value)
    assert not inputs["output"].exists()


def test_actual_source_binding_mismatch_rejected(inputs):
    inputs["pdf"].write_bytes(b"DIFFERENT SYNTHETIC SOURCE")
    with pytest.raises(ValueError, match="source differs"):
        run(inputs)
    assert not inputs["output"].exists()


@pytest.mark.parametrize("limit", ["MAX_PDF_BYTES", "MAX_RECOVERY_BYTES", "MAX_PLAN_BYTES", "MAX_IMPLEMENTATION_BYTES", "MAX_OUTPUT_BYTES"])
def test_byte_budgets_before_publication(inputs, monkeypatch, limit):
    monkeypatch.setattr(io, limit, 1)
    with pytest.raises(ValueError):
        run(inputs)
    assert not inputs["output"].exists()


@pytest.mark.parametrize("late", [False, True])
def test_cancellation_preserves_honest_publication_state(inputs, monkeypatch, late):
    original = ocr_recovery._publish_new_report

    def interrupt(temporary, destination):
        if late:
            original(temporary, destination)
        raise KeyboardInterrupt("SYNTHETIC")

    monkeypatch.setattr(ocr_recovery, "_publish_new_report", interrupt)
    with pytest.raises(KeyboardInterrupt):
        run(inputs)
    assert inputs["output"].exists() is late


def test_postcommit_cleanup_failure_preserves_complete_report(inputs, monkeypatch):
    original = ocr_recovery._publish_new_report

    def fail(temporary, destination):
        original(temporary, destination)
        raise ocr_recovery.ReportCleanupError("SYNTHETIC")

    monkeypatch.setattr(ocr_recovery, "_publish_new_report", fail)
    with pytest.raises(ocr_recovery.ReportCleanupError):
        run(inputs)
    assert json.loads(inputs["output"].read_bytes())["kind"] == "cleanup_fidelity_audit"


@pytest.mark.parametrize("growth_pass", [0, 1])
def test_each_streaming_pass_stops_at_limit_plus_one(tmp_path, monkeypatch, growth_pass):
    path = tmp_path / "synthetic"
    path.write_bytes(b"abcd")
    original = Path.open
    reads = []

    class Handle:
        def __init__(self, handle):
            self.handle, self.attempt, self.position = handle, -1, 0

        def __enter__(self):
            return self

        def __exit__(self, *args):
            self.handle.close()

        def fileno(self):
            return self.handle.fileno()

        def seek(self, offset):
            self.attempt += 1
            self.position = 0
            return self.handle.seek(offset)

        def read(self, count):
            reads.append((self.attempt, count))
            if self.attempt == growth_pass:
                self.position += count
                return b"x" * count
            return self.handle.read(count)

    monkeypatch.setattr(Path, "open", lambda self, *a, **k: Handle(original(self, *a, **k)))
    with pytest.raises(ValueError, match="streaming byte budget"):
        io._snapshot(path, 8, json_input=False)
    assert sum(count for attempt, count in reads if attempt == growth_pass) == 9


def test_digest_change_with_restored_metadata_is_detected(tmp_path, monkeypatch):
    path = tmp_path / "synthetic"
    path.write_bytes(b"abcd")
    original = Path.open

    class Handle:
        def __init__(self, handle):
            self.handle, self.attempt = handle, -1

        def __enter__(self):
            return self

        def __exit__(self, *args):
            self.handle.close()

        def fileno(self):
            return self.handle.fileno()

        def seek(self, offset):
            self.attempt += 1
            return self.handle.seek(offset)

        def read(self, count):
            data = self.handle.read(count)
            return data.replace(b"a", b"z") if self.attempt == 1 else data

    monkeypatch.setattr(Path, "open", lambda self, *a, **k: Handle(original(self, *a, **k)))
    with pytest.raises(RuntimeError, match="changed during hashing"):
        io._snapshot(path, 8, json_input=False)


def test_actual_cli_generated_only_inputs_private_replay_and_create_only(inputs):
    before = {key: digest(inputs[key]) for key in ("pdf", "recovery", "plan")}
    args = sum((["--" + key, str(inputs[key])] for key in ("pdf", "recovery", "plan", "output")), [])
    command = [sys.executable, "tools/audit_cleanup.py", *args]
    completed = subprocess.run(command, capture_output=True, text=True, timeout=30)
    assert completed.returncode == 3, completed.stderr
    assert not completed.stderr
    assert "1 changed" in completed.stdout
    assert all(str(path) not in completed.stdout for path in inputs.values())
    saved = json.loads(inputs["output"].read_bytes())
    assert saved["summary"]["changed"] == 1
    assert saved["inputs"] == {key + "_sha256": value for key, value in before.items()}
    assert "numeric_sequence_changed" in saved["entries"][0]["risks"]
    output_digest = digest(inputs["output"])
    repeated = subprocess.run(command, capture_output=True, text=True, timeout=30)
    assert repeated.returncode == 2
    assert digest(inputs["output"]) == output_digest
    assert {key: digest(inputs[key]) for key in before} == before


@pytest.mark.parametrize("difference", [-1, 0])
def test_exact_serialized_byte_limit_includes_writer_final_lf(inputs, monkeypatch, difference):
    first = dict(inputs, output=inputs["output"].with_name("size-probe.json"))
    run(first)
    size = first["output"].stat().st_size
    monkeypatch.setattr(io, "MAX_OUTPUT_BYTES", size + difference)
    if difference < 0:
        with pytest.raises(ValueError, match="output exceeds byte budget"):
            run(inputs)
        assert not inputs["output"].exists()
    else:
        run(inputs)
        assert inputs["output"].stat().st_size == size


@pytest.mark.parametrize("oversized", [False, True])
def test_staged_mutation_or_oversize_rejected_before_publication(inputs, monkeypatch, oversized):
    original = storage_policy.atomic_write_private_json

    def writer(path, report, **kwargs):
        commit = kwargs["replace_fn"]

        def corrupt(temporary, destination):
            temporary.write_bytes(b"x" * (io.MAX_OUTPUT_BYTES + 1) if oversized else b"{}\n")
            commit(temporary, destination)

        kwargs["replace_fn"] = corrupt
        return original(path, report, **kwargs)

    monkeypatch.setattr(storage_policy, "atomic_write_private_json", writer)
    with pytest.raises((ValueError, RuntimeError)):
        run(inputs)
    assert not inputs["output"].exists()
