"""Real optional Gradio consent wiring over generated geometry and fixed inputs.

Only the display renderer is replaced. No PDF, browser, OCR or model executes.
Suggestions remain transient; preview and export are distinct operator claims.
"""
from __future__ import annotations

import asyncio
import copy
import hashlib
import json
from pathlib import Path
from types import SimpleNamespace

import pytest

import ocr_docling
import ocr_recovery
import storage_policy
from ocr_review_drafts import build_draft, initial_state
from ocr_review_runtime import ReviewWorkspace


def _candidate():
    bounds = [(80, 50, 800, 100)]
    for y in (300, 400, 500):
        bounds.extend([(100, y, 350, y + 50), (600, y, 850, y + 50)])
    bounds.append((80, 900, 700, 940))
    lines = [{"text": f"Synthetic occurrence {index}", "score": .9,
              "box": [[left, top], [right, top], [right, bottom], [left, bottom]]}
             for index, (left, top, right, bottom) in enumerate(bounds)]
    return {"text": "\n".join(line["text"] for line in lines), "lines": lines, "mean_confidence": .9,
            "raster": {"width": 1000, "height": 1000, "dpi": 300, "coordinate_system": "rendered_image_pixels"},
            "engine": {"name": "rapidocr", "version": "synthetic-no-execution", "min_score": 0., "max_side": 6000}}


def _document():
    document = {"schema_name": "DoclingDocument", "version": "1.0.0",
                "pages": {str(number): {"page_no": number, "size": {"width": 240, "height": 240}}
                           for number in (1, 2)}, "texts": [], "tables": [], "pictures": [], "groups": [],
                "body": {"self_ref": "#/body", "children": []},
                "furniture": {"self_ref": "#/furniture", "children": []}}
    for number in (1, 2):
        for tree, bounds in (("furniture", (50, 20, 950, 150)), ("body", (50, 250, 450, 600)),
                             ("body", (550, 250, 950, 600)), ("furniture", (50, 850, 950, 980))):
            ref = f"#/texts/{len(document['texts'])}"
            left, top, right, bottom = [value * .24 for value in bounds]
            document["texts"].append({"self_ref": ref, "label": "text", "text": "Synthetic region",
                "children": [], "prov": [{"page_no": number, "bbox": {
                    "l": left, "t": top, "r": right, "b": bottom, "coord_origin": "TOPLEFT"}}]})
            document[tree]["children"].append({"$ref": ref})
    return document


@pytest.fixture
def workspace(tmp_path):
    source = tmp_path / "synthetic-source.bin"
    source.write_bytes(b"Generated bytes only; no PDF renderer is used by these tests.")

    class Reader:
        page_count = 2

        def native_text(self, _number):
            return ""

        def retry(self, _number):
            return _candidate()

    recovery = ocr_recovery.build_recovery_report(Reader(), source_sha256=hashlib.sha256(source.read_bytes()).hexdigest(),
        policy=ocr_recovery.RetryPolicy(), requested_pages=(1, 2))
    recovery["evidence_sha256"] = None
    saved = tmp_path / "recovery.json"
    saved.write_text(json.dumps(recovery), encoding="utf-8")
    proposals = ocr_docling.build_docling_proposals(_document(), recovery,
        recovery_sha256=hashlib.sha256(saved.read_bytes()).hexdigest(), docling_sha256="c" * 64,
        manifest_sha256="d" * 64, effective_input_kind="original")
    proposal_path = tmp_path / "proposals.json"
    proposal_path.write_text(json.dumps(proposals), encoding="utf-8")
    first = ReviewWorkspace(source, saved, tmp_path, proposals_path=proposal_path)
    draft = build_draft(initial_state(first.document), first.document,
        proposals=first.proposals, proposals_sha256=first.proposals_sha256)
    draft_path = tmp_path / "fixed-draft.json"
    draft_path.write_text(json.dumps(draft), encoding="utf-8")
    return ReviewWorkspace(source, saved, tmp_path, draft_path=draft_path, proposals_path=proposal_path)


def _configure_download_cache(workspace, monkeypatch):
    """Match the launcher cache boundary for each generated test workspace."""
    cache = storage_policy.ensure_private_directory(workspace.output_dir / "ocr-review-cache-test")
    monkeypatch.setenv("GRADIO_TEMP_DIR", str(cache))


@pytest.fixture
def ui(workspace, monkeypatch):
    _configure_download_cache(workspace, monkeypatch)
    monkeypatch.setenv("GRADIO_ANALYTICS_ENABLED", "False")
    pytest.importorskip("gradio")
    Image = pytest.importorskip("PIL.Image")
    import ocr_review_ui

    renders, overlays = [], []

    def render(number):
        renders.append(number)
        return Image.new("RGB", (100, 100), "white")

    original_overlay = ocr_review_ui.draw_overlay

    def overlay(*args, **kwargs):
        overlays.append(copy.deepcopy(kwargs))
        return original_overlay(*args, **kwargs)

    monkeypatch.setattr(workspace, "render", render)
    monkeypatch.setattr(ocr_review_ui, "draw_overlay", overlay)
    app = ocr_review_ui.build_app(workspace)
    functions = {block.fn.__name__: block.fn for block in app.fns.values() if block.fn is not None}
    state = copy.deepcopy(next(block.value for block in app.blocks.values() if type(block).__name__ == "State"))
    yield SimpleNamespace(app=app, functions=functions, state=state, workspace=workspace,
                          renders=renders, overlays=overlays)
    app.close()


def _suggest(ui, state=None):
    result = ui.functions["suggest_columns"](copy.deepcopy(ui.state if state is None else state))
    assert len(result) == 7 and result[4:6] == (False, False)
    return result


def _export(ui, label):
    return next(block.fn for block in ui.app.fns.values() if block.fn is not None
                and any(getattr(component, "label", None) == label for component in block.inputs))


def _manual_preview(ui):
    state = copy.deepcopy(ui.state)
    state["selections"] = {"body": [0, .2, 1, .7], "gutter": [.45, .2, .55, .7]}
    return ui.functions["preview"](state, False, state["column_context"])[1]


def test_suggestion_is_transient_and_has_original_text_numbering_without_writes(ui):
    before = copy.deepcopy(ui.state)
    files = set(ui.workspace.output_dir.iterdir())
    _, state, proposed, difference, _, _, _ = _suggest(ui)
    assert state.get("column_suggestion") is not None
    assert state["layouts"] == before["layouts"] == []
    assert state["selections"] == before["selections"] == {}
    assert state["line_order"] is None
    assert state["history"] == before["history"]
    assert proposed == ui.workspace.document.page_text(1)
    assert difference == "No text differences."
    assert ui.overlays[-1]["line_order"] is None
    assert set(ui.workspace.output_dir.iterdir()) == files
    assert ui.state == before


@pytest.mark.parametrize("confirmed", [False, None, 0, 1, "true", [], {}])
def test_existing_preview_cannot_bypass_pending_prose_consent(ui, confirmed):
    state = _suggest(ui)[1]
    before = copy.deepcopy(state)
    with pytest.raises(Exception, match="Review action failed"):
        ui.functions["preview"](state, confirmed, state.get("column_context"))
    assert state == before and state["layouts"] == []


def test_explicit_prose_preview_then_separate_export_confirmation(ui):
    state = _suggest(ui)[1]
    _, state, proposed, difference, confirmed, _ = ui.functions["preview"](state, True, state["column_context"])
    assert confirmed is False and state.get("column_suggestion") is None
    assert len(state["layouts"]) == 1 and state["layouts"][0]["page_number"] == 1
    assert state["selections"].keys() >= {"body", "gutter"}
    assert state["line_order"] == [0, 1, 3, 5, 2, 4, 6, 7]
    assert proposed != ui.workspace.document.page_text(1) and "--- original" in difference
    handler = _export(ui, "I reviewed the numbered order and text differences")
    for rejected in (False, 1, "true", None):
        with pytest.raises(Exception, match="Review action failed"):
            handler(rejected, state, state["column_context"])
    path, _ = handler(True, state, state["column_context"])
    saved = json.loads(Path(path).read_bytes())
    assert saved == ui.workspace.document.layout_plan(state["layouts"])


def test_new_suggestion_preserves_old_plan_but_displays_original_then_dismiss_restores(ui):
    previous = _manual_preview(ui)
    result = _suggest(ui, previous)
    pending = result[1]
    assert pending["layouts"] == previous["layouts"]
    assert pending["selections"] == previous["selections"]
    assert pending["line_order"] == previous["line_order"]
    assert result[2] == ui.workspace.document.page_text(1)
    assert ui.overlays[-1]["line_order"] is None
    dismissed = ui.functions["dismiss_column_suggestion"](pending)
    assert len(dismissed) == 7 and dismissed[4:6] == (False, False)
    assert dismissed[1].get("column_suggestion") is None
    assert dismissed[1]["layouts"] == previous["layouts"]
    assert dismissed[2] != result[2]


@pytest.mark.parametrize("label,method", [
    ("I reviewed the numbered order and text differences", None),
    ("I reviewed all stored Docling page orders against the scan", "docling_review"),
    ("I reviewed every previewed assignment page against the scan", "assignment_review")])
def test_pending_suggestion_blocks_all_order_exports_even_prior_stored_plans(ui, monkeypatch, label, method):
    state = _suggest(ui, _manual_preview(ui))[1]
    if method:
        monkeypatch.setattr(ui.workspace, method, lambda *a, **k: pytest.fail("pending suggestion reached review producer"))
    files = set(ui.workspace.output_dir.iterdir())
    with pytest.raises(Exception, match="Review action failed"):
        _export(ui, label)(True, state, state["column_context"])
    assert set(ui.workspace.output_dir.iterdir()) == files


def test_suggestion_only_draft_restart_cannot_become_manual_preview(ui, monkeypatch):
    state = _suggest(ui)[1]
    _, path, _ = ui.functions["save_draft"]("unfinished reference", state, state["annotation_context"])
    payload = json.loads(Path(path).read_bytes())
    assert "column_suggestion" not in payload
    assert payload["selections"] == {} and payload["layouts"] == []
    loaded = ReviewWorkspace(ui.workspace.pdf_path, ui.workspace.recovery_path, ui.workspace.output_dir,
        draft_path=Path(path), proposals_path=ui.workspace.proposals_path)
    assert loaded.initial_draft.get("column_suggestion") is None
    assert loaded.initial_draft["line_order"] is None
    monkeypatch.setattr(loaded, "render", ui.workspace.render)
    from ocr_review_ui import build_app
    app = build_app(loaded)
    try:
        assert all(block.value is False for block in app.blocks.values() if type(block).__name__ == "Checkbox")
        preview = next(block.fn for block in app.fns.values() if block.fn is not None and block.fn.__name__ == "preview")
        with pytest.raises(Exception, match="Review action failed"):
            restored = copy.deepcopy(next(block.value for block in app.blocks.values() if type(block).__name__ == "State"))
            preview(restored, False, restored["column_context"])
    finally:
        app.close()


@pytest.mark.parametrize("action", ["change_page", "change_tool", "clear_selection", "select_rectangle",
                                    "preview_docling", "start_assignments"])
def test_navigation_selection_and_competing_review_actions_clear_pending(ui, action):
    state = _suggest(ui)[1]
    if action == "change_page":
        result = ui.functions[action](2, state, view_context=state["annotation_context"])
        state = result[7]
    elif action == "select_rectangle":
        state = ui.functions[action](state, "crop", SimpleNamespace(index=[10, 20]), state["annotation_context"])[1]
    elif action in {"change_tool", "clear_selection"}:
        state = ui.functions[action](state, state["annotation_context"])[1]
    else:
        state = ui.functions[action](state)[1]
    assert state.get("column_suggestion") is None


@pytest.mark.parametrize("field", ["pdf_path", "recovery_path", "draft_path", "proposals_path"])
@pytest.mark.parametrize("action", ["suggest", "preview"])
def test_changed_full_generation_refused_even_with_cached_scan(ui, field, action):
    state = _suggest(ui)[1] if action == "preview" else copy.deepcopy(ui.state)
    render_count = len(ui.renders)
    getattr(ui.workspace, field).write_bytes(b"SYNTHETIC_PRIVATE_REPLACEMENT")
    with pytest.raises(Exception, match="Review action failed") as error:
        ui.functions["suggest_columns"](state) if action == "suggest" else ui.functions["preview"](state, True, state["column_context"])
    assert "SYNTHETIC_PRIVATE" not in str(error.value)
    assert len(ui.renders) == render_count
    assert state["layouts"] == [] and not list(ui.workspace.output_dir.glob("ocr-layout-*.json"))


@pytest.mark.parametrize("action", ["suggest", "preview"])
def test_replaced_output_directory_identity_refuses_pending_actions(ui, monkeypatch, action):
    state = _suggest(ui)[1] if action == "preview" else ui.state
    monkeypatch.setattr(ui.workspace, "_directory_generation", lambda: (-1, -1))
    with pytest.raises(Exception, match="Review action failed"):
        ui.functions["suggest_columns"](state) if action == "suggest" else ui.functions["preview"](state, True, state["column_context"])


def test_forged_or_cross_page_pending_report_cannot_materialize_layout(ui):
    state = _suggest(ui)[1]
    forged = copy.deepcopy(state)
    forged["column_suggestion"]["source_sha256"] = "f" * 64
    crossed = copy.deepcopy(state)
    crossed["page"] = 2
    for bad in (forged, crossed):
        with pytest.raises(Exception, match="Review action failed"):
            ui.functions["preview"](bad, True, bad["column_context"])
        assert bad["layouts"] == []


def test_workspace_rechecks_after_suggestion_computation(workspace, monkeypatch):
    import ocr_column_suggestions
    original = ocr_column_suggestions.build_column_suggestions

    def mutate(*args, **kwargs):
        result = original(*args, **kwargs)
        workspace.recovery_path.write_bytes(b"changed after suggestion computation")
        return result

    monkeypatch.setattr(ocr_column_suggestions, "build_column_suggestions", mutate)
    with pytest.raises(RuntimeError, match="changed"):
        workspace.column_suggestion(1)


def test_gradio_suggestion_and_preview_have_explicit_private_click_only_paths(ui):
    app = ui.app
    dependencies = app.config["dependencies"]
    for dependency in dependencies:
        assert dependency["api_visibility"] == "private"
    named = {block.fn.__name__: (index, block) for index, block in app.fns.items() if block.fn is not None}
    suggest_index, suggest = named["suggest_columns"]
    preview_index, preview = named["preview"]
    assert suggest.concurrency_id == preview.concurrency_id == "ocr-review"
    assert suggest.concurrency_limit == preview.concurrency_limit == 1
    preview_dependency = next(item for item in dependencies if item["id"] == preview_index)
    assert preview_dependency["trigger_after"] is None
    assert all(event == "click" for _, event in preview_dependency["targets"])
    prose = next(component for component in preview.inputs if type(component).__name__ == "Checkbox")
    assert prose.value is False and "prose" in prose.label.lower() and "table" in prose.label.lower()
    assert "left-to-right" in prose.label.lower()
    ancestors = {suggest_index}
    for _ in range(len(dependencies)):
        ancestors.update(item["id"] for item in dependencies if item["trigger_after"] in ancestors)
    assert preview_index not in ancestors
    for dependency in dependencies:
        if any(component == prose._id for component, _ in dependency["targets"]):
            assert dependency["id"] != preview_index
    assert all(type(component).__name__ != "Checkbox" for component in suggest.inputs)


def _block(ui, name):
    return next(block for block in ui.app.fns.values() if block.fn is not None and block.fn.__name__ == name)


async def _capture_queued(ui, block, inputs, *, session_hash):
    """Use the installed transport queue's real retained request input body."""
    from fastapi import Request
    from gradio.data_classes import PredictBodyInternal

    request = Request({"type": "http", "method": "POST", "path": "/gradio_api/queue/join",
                       "root_path": "", "headers": [], "query_string": b"", "scheme": "http",
                       "server": ("127.0.0.1", 7860), "client": ("127.0.0.1", 1)})
    index = next(index for index, candidate in ui.app.fns.items() if candidate is block)
    body = PredictBodyInternal(data=copy.deepcopy(inputs), fn_index=index,
                               session_hash=session_hash, request=request)
    accepted, event_id, status = await ui.app._queue.push(body, request, None)
    assert accepted and status == "success"
    event = ui.app._queue.event_ids_to_events[event_id]
    assert event.data.data == inputs and event.concurrency_id == "ocr-review"
    return event


async def _process(ui, block, inputs, session, session_hash):
    return await ui.app.process_api(block, inputs=inputs, state=session, session_hash=session_hash)


@pytest.mark.parametrize("synchronize", [False, True])
def test_queued_previous_page_prose_confirmation_cannot_preview_new_suggestion(ui, synchronize):
    """A real queued old token + True cannot consume the newer live State."""
    async def scenario():
        session_hash = "generated-stale-column-preview"
        session = ui.app.state_holder[session_hash]
        preview = _block(ui, "preview")
        state_id = preview.inputs[0]._id
        first = _suggest(ui)[1]
        session[state_id] = first
        queued = await _capture_queued(ui, preview, [None, True, first["column_context"]], session_hash=session_hash)
        await _process(ui, _block(ui, "change_page"), [2, None, "", first["annotation_context"]], session, session_hash)
        response = await _process(ui, _block(ui, "suggest_columns"), [None], session, session_hash)
        assert response["data"][4:6] == [False, False]
        current = copy.deepcopy(session[state_id])
        assert current["page"] == 2 and current["column_context"] != first["column_context"]
        if synchronize:
            synced = await _process(ui, _block(ui, "sync_column_context"), [None], session, session_hash)
            assert synced["data"] == [current["column_context"], False, False, False, False]
        with pytest.raises(Exception, match="Review action failed"):
            await _process(ui, queued.fn, queued.data.data, session, session_hash)
        assert session[state_id] == current and current["layouts"] == []
        assert not list(ui.workspace.output_dir.glob("ocr-layout-*.json"))

    asyncio.run(scenario())


@pytest.mark.parametrize("label", [
    "I reviewed the numbered order and text differences",
    "I reviewed all stored Docling page orders against the scan",
    "I reviewed every previewed assignment page against the scan",
])
@pytest.mark.parametrize("synchronize", [False, True])
def test_queued_order_export_cannot_reuse_confirmation_after_new_preview(ui, label, synchronize):
    async def scenario():
        session_hash = "generated-stale-column-export"
        session = ui.app.state_holder[session_hash]
        preview = _block(ui, "preview")
        state_id = preview.inputs[0]._id
        pending = _suggest(ui)[1]
        export = next(block for block in ui.app.fns.values() if block.fn is not None
                      and any(getattr(component, "label", None) == label for component in block.inputs))
        session[state_id] = pending
        queued = await _capture_queued(ui, export, [True, None, pending["column_context"]], session_hash=session_hash)
        accepted = await _process(ui, preview, [None, True, pending["column_context"]], session, session_hash)
        assert accepted["data"][4] is False
        current = copy.deepcopy(session[state_id])
        assert current["column_context"] != pending["column_context"] and len(current["layouts"]) == 1
        if synchronize:
            synced = await _process(ui, _block(ui, "sync_column_context"), [None], session, session_hash)
            assert synced["data"] == [current["column_context"], False, False, False, False]
        with pytest.raises(Exception, match="Review action failed"):
            await _process(ui, queued.fn, queued.data.data, session, session_hash)
        assert session[state_id] == current
        assert not list(ui.workspace.output_dir.glob("ocr-layout-*.json"))

    asyncio.run(scenario())


def test_matching_synchronized_client_context_allows_explicit_preview_and_export(ui):
    async def scenario():
        session_hash = "generated-current-column-context"
        session = ui.app.state_holder[session_hash]
        preview = _block(ui, "preview")
        state_id = preview.inputs[0]._id
        session[state_id] = copy.deepcopy(ui.state)
        await _process(ui, _block(ui, "suggest_columns"), [None], session, session_hash)
        first = await _process(ui, _block(ui, "sync_column_context"), [None], session, session_hash)
        assert first["data"][1:] == [False] * 4
        queued = await _capture_queued(ui, preview, [None, True, first["data"][0]], session_hash=session_hash)
        await _process(ui, queued.fn, queued.data.data, session, session_hash)
        second = await _process(ui, _block(ui, "sync_column_context"), [None], session, session_hash)
        assert second["data"][1:] == [False] * 4 and first["data"][0] != second["data"][0]
        export = next(block for block in ui.app.fns.values() if block.fn is not None and any(
            getattr(component, "label", None) == "I reviewed the numbered order and text differences"
            for component in block.inputs))
        queued = await _capture_queued(ui, export, [True, None, second["data"][0]], session_hash=session_hash)
        await _process(ui, queued.fn, queued.data.data, session, session_hash)
        paths = list(ui.workspace.output_dir.glob("ocr-layout-*.json"))
        assert len(paths) == 1
        assert json.loads(paths[0].read_bytes())["pages"] == session[state_id]["layouts"]

    asyncio.run(scenario())


@pytest.mark.parametrize("value", [None, "", "stale", True, 1])
def test_missing_or_wrong_client_context_cannot_bypass_sticky_session(ui, value):
    pending = _suggest(ui)[1]
    with pytest.raises(Exception, match="Review action failed"):
        ui.functions["preview"](pending, True, value)
    dismissed = ui.functions["dismiss_column_suggestion"](pending)[1]
    assert dismissed["column_context"] is not None and dismissed["column_context"] != pending["column_context"]
    with pytest.raises(Exception, match="Review action failed"):
        _export(ui, "I reviewed the numbered order and text differences")(True, dismissed, value)


def test_context_sync_checks_generation_and_sanitizes_errors(ui, monkeypatch):
    pending = _suggest(ui)[1]

    def fail():
        raise OSError("SYNTHETIC_PRIVATE_PATH_AND_DETAILS")

    monkeypatch.setattr(ui.workspace, "verify_inputs", fail)
    with pytest.raises(Exception, match="Review action failed") as error:
        ui.functions["sync_column_context"](pending)
    assert "SYNTHETIC_PRIVATE" not in str(error.value)


def test_initial_view_has_a_real_client_context_before_any_suggestion(ui):
    preview = _block(ui, "preview")
    context = preview.inputs[2]
    assert type(context).__name__ == "Textbox" and context.stateful is False
    assert context.visible is False and context.value == ui.state["column_context"]
    assert isinstance(context.value, str) and len(context.value) == 32
    assert ui.state.get("column_suggestion") is None


def test_queued_manual_preview_cannot_reuse_initial_view_after_tool_change(ui):
    async def scenario():
        session_hash = "generated-initial-manual-preview"
        session = ui.app.state_holder[session_hash]
        preview = _block(ui, "preview")
        state_id = preview.inputs[0]._id
        initial = copy.deepcopy(ui.state)
        initial["selections"] = {"body": [0, .2, 1, .7], "gutter": [.45, .2, .55, .7]}
        session[state_id] = initial
        queued = await _capture_queued(ui, preview, [None, False, initial["column_context"]], session_hash=session_hash)
        await _process(ui, _block(ui, "change_tool"), [None, initial["annotation_context"]], session, session_hash)
        current = copy.deepcopy(session[state_id])
        assert current["column_context"] != initial["column_context"]
        with pytest.raises(Exception, match="Review action failed"):
            await _process(ui, queued.fn, queued.data.data, session, session_hash)
        assert session[state_id] == current and current["layouts"] == []

    asyncio.run(scenario())


@pytest.mark.parametrize("kind,action,label", [
    ("layout", "preview", "I reviewed the numbered order and text differences"),
    ("docling", "preview_docling", "I reviewed all stored Docling page orders against the scan"),
    ("assignment", "preview_assignments", "I reviewed every previewed assignment page against the scan"),
])
@pytest.mark.parametrize("synchronize", [False, True])
def test_all_order_exports_are_context_bound_before_any_column_suggestion(ui, kind, action, label, synchronize):
    async def scenario():
        session_hash = "generated-initial-order-export"
        session = ui.app.state_holder[session_hash]
        preview = _block(ui, "preview")
        state_id = preview.inputs[0]._id
        initial = copy.deepcopy(ui.state)
        initial["selections"] = {"body": [0, .2, 1, .7], "gutter": [.45, .2, .55, .7]}
        session[state_id] = initial
        export = next(block for block in ui.app.fns.values() if block.fn is not None
                      and any(getattr(component, "label", None) == label for component in block.inputs))
        queued = await _capture_queued(ui, export, [True, None, initial["column_context"]], session_hash=session_hash)
        if kind == "assignment":
            await _process(ui, _block(ui, "start_assignments"), [None], session, session_hash)
        inputs = [None, False, initial["column_context"]] if kind == "layout" else [None]
        await _process(ui, _block(ui, action), inputs, session, session_hash)
        current = copy.deepcopy(session[state_id])
        assert current["column_context"] != initial["column_context"] and current.get("column_suggestion") is None
        if synchronize:
            synced = await _process(ui, _block(ui, "sync_column_context"), [None], session, session_hash)
            assert synced["data"] == [current["column_context"], False, False, False, False]
        with pytest.raises(Exception, match="Review action failed"):
            await _process(ui, queued.fn, queued.data.data, session, session_hash)
        assert session[state_id] == current and not list(ui.workspace.output_dir.glob(f"ocr-{kind}-*.json"))
        # Explicitly recaptured current view + affirmative consent still works.
        synced = await _process(ui, _block(ui, "sync_column_context"), [None], session, session_hash)
        fresh = await _capture_queued(ui, export, [True, None, synced["data"][0]], session_hash=session_hash)
        await _process(ui, fresh.fn, fresh.data.data, session, session_hash)
        assert len(list(ui.workspace.output_dir.glob(f"ocr-{kind}-*.json"))) == 1

    asyncio.run(scenario())
